server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/com/ftx/solution/core/config
#        git:
#          uri: git地址
#          search-paths: 仓库路径
#          label：分支
#          username：账号
#          password：密码
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
