server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    service-auth:
      path: /uaa/**
      stripPrefix: false
      sensitiveHeaders:
    management-example:
      path: /management/**
      sensitiveHeaders:
    service-example:
      path: /service/**
      sensitiveHeaders: